[project]
name = "otel-tracing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opentelemetry-api>=1.37.0",
    "opentelemetry-sdk>=1.37.0",
]

[dependency-groups]
dev = [
    "fastapi>=0.116.1",
]
